##DynamoDB
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  csye6225:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"

      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "csye6225"

##RDS Instance
# csye6225:
#   Type: AWS::RDS::DBInstance
#   Properties:
#     Engine: "MySQL"
#     DBInstanceClass:
#       Ref: "db.t2.medium"
#     MultiAZ:
#       Ref: "false"
#     DBInstanceIdentifier:
#       Ref: "csye6225-spring2019"
#     MasterUsername:
#       Ref: "csye6225master"
#     MasterUserPassword:
#       Ref: "csye6225password"
#     PubliclyAccessible:
#       Ref: "true"
#     DBSubnetGroupName:
#       Ref: "Subnet for RDS instances" #TODO
#     DBName:
#       Ref: "csye6225"